//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVGS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int AddressID { get; set; }
        public int MemberID { get; set; }
        public string UnitAndStreet { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public int ProvinceID { get; set; }
        public bool? IsSame { get; set; }
        public bool IsMailingAddress { get; set; }
        public int CountryID { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Province Province { get; set; }
        public virtual User User { get; set; }
    }
}
