//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVGS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.EventRegistrations = new HashSet<EventRegistration>();
        }
    
        public int EventID { get; set; }
        [Required]
        [StringLength(40, ErrorMessage = "Name should not exceed limit")]
        [Display(Name = "Event Name")]
        public string EventName { get; set; }

        [Required]
        [Display(Name = "Event Description")]
        [StringLength(240, ErrorMessage = "Description should not exceed limit")]
        public string EventDescription { get; set; }

        [Display(Name = "Event Date")]
        [Required(ErrorMessage = "Event Date is required.")]
        [DataType(DataType.Date)]
        public System.DateTime EventDate { get; set; }

        [DisplayName("Upload Picture")]
        public string ImageURL { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventRegistration> EventRegistrations { get; set; }
    }
}
